import type { Nuxt } from 'nuxt/schema';
import type { Nitro } from 'nitropack/types';
import { addTemplate } from 'nuxt/kit';

type Unimport = Nitro['unimport'];

export function setupOxlint(nuxt: Nuxt) {
  let unImport: Unimport | undefined;
  let nitroUnImport: Unimport | undefined;

  nuxt.hook('imports:context', (context: Unimport) => {
    unImport = context;
  });

  // oxlint-disable-next-line
  // @ts-ignore - weird bug with tsgo
  nuxt.hook('nitro:init', (nitro: Nitro) => {
    nitroUnImport = nitro.unimport;
  });

  addTemplate({
    write: true,
    filename: 'oxlint.mjs',
    async getContents() {
      return [
        `// This file is auto-generated by the oxc Nuxt module. Do not edit it manually.`,
        `const globals = ${JSON.stringify(await generateGlobals(unImport, nitroUnImport))};`,
        '',
        `export function withNuxt(config) {`,
        `  return {`,
        `    ...config,`,
        `    plugins: config.plugins ?? ['typescript', 'oxc', 'import', 'vue', 'promise'],`,
        `    globals: { ...globals, ...config.globals },`,
        `  };`,
        `}`,
      ].join('\n');
    },
  });

  addTemplate({
    write: true,
    filename: 'oxlint.d.mts',
    getContents() {
      return [
        `// This file is auto-generated by the oxc Nuxt module. Do not edit it manually.`,
        `import type { OxlintConfig } from 'oxlint';`,
        '',
        `/**`,
        ` * Utility function to merge the auto-generated globals with a custom Oxc config.`,
        ` * This is useful if you want to extend the globals with your own custom globals or override the default ones.`,
        ` */`,
        `export declare function withNuxt(config: OxlintConfig): OxlintConfig;`,
      ].join('\n');
    },
  });
}

async function generateGlobals(unImport: Unimport | undefined, nitroUnImport: Unimport | undefined) {
  const unImports = await Promise.all([unImport?.getImports(), nitroUnImport?.getImports()].filter((i) => !!i));

  const sortedImports = unImports
    .flat()
    .sort((a, b) => 10 * a.from.localeCompare(b.from) + a.name.localeCompare(b.name))
    .map((i) => i.as ?? i.name);

  sortedImports.unshift('defineNuxtConfig');
  const globals = Object.fromEntries(sortedImports.map((i) => [i, 'readonly'] as const));
  return globals;
}
